### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by TovaToba** [r3d5ky/sercomm_cfg_unpacker#1]
Traceback (most recent call last):
  File "C:\Users\97156\Downloads\S3\cfgtool.py", line 79, in <module>
    main()
  File "C:\Users\97156\Downloads\S3\cfgtool.py", line 71, in main
    unpack(args.file, args.raw)
  File "C:\Users\97156\Downloads\S3\cfgtool.py", line 31, in unpack
    unpacked = zlib.decompress(infile[4:])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check

on further checking the configurationbackup.cfg: 
first_bytes = file.read(10)
first_bytes
RESULT: b'FW Version'

**Comment by r3d5ky** [comment]
Looks like you have incorrect or incompatible config file. Can you attach it here? And what is your firmware version?

**Comment by kuzakoff** [comment]
Sercomm RV6699v2 v4.2.40
[gponcfg.zip](https://github.com/r3d5ky/sercomm_cfg_unpacker/files/12434627/gponcfg.zip)

**Comment by kuzakoff** [comment]
> Looks like you have incorrect or incompatible config file. Can you attach it here? And what is your firmware version?

Sercomm RV6699v2 v4.2.40
[gponcfg.zip](https://github.com/r3d5ky/sercomm_cfg_unpacker/files/12434651/gponcfg.zip)

**Comment by r3d5ky** [comment]
> Sercomm RV6699v2 v4.2.40 [gponcfg.zip](https://github.com/r3d5ky/sercomm_cfg_unpacker/files/12434651/gponcfg.zip)

You have completely different config format, it is encrypted with AES or RSA (i don't remember exactly, found that in libraries from firmware of your device), decryption keys are initialized in working system, and as i don't have that device, i couldn't extract that keys or find from which binary/library they are created. Maybe if i have spare time, i'll try to dig deeper into firmware and find out how to make that keys (maybe they are generated from serial number or other stuff) or where to find them.

**Comment by fsa** [comment]
Sercomm RT-GM-1 (Rostelecom)
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by r3d5ky** [comment]
> Sercomm RT-GM-1 (Rostelecom) zlib.error: Error -3 while decompressing data: incorrect header check

Attach your config file, so i can look at it. Initially this script was created and tested on a few models, mainly on S1010 variations, so it couldn't work on all Sercomm devices.

**Comment by edisionnano** [comment]
[configurationBackup.cfg.zip](https://github.com/r3d5ky/sercomm_cfg_unpacker/files/13442676/configurationBackup.cfg.zip)
This is from the SHG3000, encrypted in 2048bit aes
![image](https://github.com/r3d5ky/sercomm_cfg_unpacker/assets/26039434/4a932f60-92bd-4406-9d06-4f8887b7a961)
Web UI asks for password, I was able to bypass that by resending the request with password ""

**Comment by tonyp740613** [comment]
I exported the config file but it saved it with a .rom extension and I have a passphrase which must be used when restoring it back to the device
[backup-S3ZA-2024-07-20.zip](https://github.com/user-attachments/files/16321232/backup-S3ZA-2024-07-20.zip)
Firmware version: S3ES1-V1.0.24

**Comment by r3d5ky** [comment]
> I exported the config file but it saved it with a .rom extension and I have a passphrase which must be used when restoring it back to the device [backup-S3ZA-2024-07-20.zip](https://github.com/user-attachments/files/16321232/backup-S3ZA-2024-07-20.zip) Firmware version: S3ES1-V1.0.24

What is your device? And can you provide firmware update file or partition dump?

**Comment by tonyp740613** [comment]
It appears to be similar to the Etisalat S3 router but it is branded with my service provider logo and locked down.  There are no firmware update files available to download.

[https://openwrt.org/toh/etisalat/s3](url)

**Comment by titchy** [comment]
I also have a Vodacom branded Etisalat S3 which is exporting a .rom file and password when saving the configuration.
It is a raw router so I am happy to uplad config and password.
Password: o6IrHj3f3KUz1OfN
[backup-S3ZA-2024-08-22.zip](https://github.com/user-attachments/files/16707219/backup-S3ZA-2024-08-22.zip)

I have not yet been able to look into what encryption they are using to save the file.
